name: Lint

on: push

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: install poetry
        run: pip install poetry
        
      - name: set up poetry
        run: make install
        
      - name: Run Wemake Python Styleguide
        run: make lint
